### PR TITLE
fixes collection view and label filters for languages

### PR DESCRIPTION
**Pull request by rob-metalinkage**

### CODE REVIEW

**Comment by rob-metalinkage** [comment]
check the conflict in source.py - i thinks its something you may have fixed or superceded and you can ignore.

**Comment by nicholascar** [comment]
@rob-metalinkage I can't merge this PR since you've removed the graph awareness in the `get_concept_hierarchy()` function inside `_source.py`. Other instances of VP have vocabs within Named Graphs so this change will break them.

The solution is to implement the function `get_concept_hierarchy()`  as you need it in your OGC theme's own source, just as I've done with `get_collection()` with the original being at https://github.com/RDFLib/VocPrez/blob/master/vocprez/source/_source.py#L160 and your OGC one at https://github.com/surroundaustralia/VocPrez-theme-ogc/blob/master/source/ogc_sparql.py#L17.

I'll try and remove this change from this PR, accept the others and then re-implement the change in your theme repo.

**Comment by rob-metalinkage** [comment]
are you sure - I have actually respected an explicit inScheme over graph containment (which is an implicit pattern) , but it should still work..

         GRAPH ?g {
                    <xxxx> a skos:Collection ;
                    BIND ( COALESCE( ?cs,?g) AS ?conceptscheme )

**Comment by rob-metalinkage** [comment]
that said - it is probably incomplete - list_collections should also respect explicit rather than implicit containment.

**Comment by rob-metalinkage** [comment]
I dont think this is a theme repo issue - its relaxing an idiosyncratic implementation requirement to handle a more general case by preference.  If an application needs to _ignore_ an explicit statement, then _that application_ should override the SKOS model rather than the other way around

**Pull request merged**
